question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called Backrub.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was Moon.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from the Moon.", "answer": "False"},
    {"text": "Light takes approximately 8 minutes to travel from the Sun to the Earth.", "answer": "True"},
    {"text": "Humans and dinosaurs co-existed at the same time.", "answer": "False"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"text": "Adult humans have fewer bones than babies do.", "answer": "True"},
    {"text": "The inventor of the lightbulb was Thomas Edison.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The Sahara is the largest desert in the world by area.", "answer": "False"},
    {"text": "Venus is the hottest planet in our solar system.", "answer": "True"},
    {"text": "Sound travels faster in air than in water.", "answer": "False"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "Mount Kilimanjaro is the tallest mountain in the world.", "answer": "False"},
    {"text": "The human adult body has four lungs.", "answer": "False"},
    {"text": "The boiling point of water at sea level is 100 degrees Celsius.", "answer": "True"},
    {"text": "Shakespeare wrote the novel 'Moby Dick'.", "answer": "False"},
    {"text": "The currency of Japan is the Yen.", "answer": "True"},
    {"text": "A heptagon has eight sides.", "answer": "False"},
    {"text": "The human heart has four chambers.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "The primary language of Brazil is Portuguese.", "answer": "True"},
    {"text": "An adult koala is carnivorous.", "answer": "False"},
    {"text": "The Pacific Ocean is larger than the Atlantic Ocean.", "answer": "True"},
    {"text": "The capital city of Australia is Sydney.", "answer": "False"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "The human skeleton is made entirely of bone; there is no cartilage.", "answer": "False"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "There are 365 days in a leap year.", "answer": "False"},
    {"text": "A nanometer is one billionth of a meter.", "answer": "True"},
    {"text": "The largest organ in the human body is the skin.", "answer": "True"},
    {"text": "The Mona Lisa was painted by Leonardo da Vinci.", "answer": "True"},
    {"text": "Sound can travel through a vacuum.", "answer": "False"},
    {"text": "The shortest day of the year in the northern hemisphere is the Winter Solstice.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The Eiffel Tower is located in Berlin.", "answer": "False"},
    {"text": "Water freezes at 0 degrees Celsius at sea level.", "answer": "True"}
]
